organization:
  name: "Biddly"
#  custom_description: "Foo <b>Bar</b>"
  
keycloak:
  url: "http://localhost:8082"
  realm: "cloak-apps-realm"
  client_id: "cloak-apps-portal"
  client_secret: "<PASTE_CLIENT_SECRET_FROM_KEYCLOAK>"
  redirect_uri: "http://localhost:8080/auth/callback"

server:
  port: 8080
#  host: "localhost"
#  timeout: 10
  log_level: "DEBUG"

session:
  secret: "<GENERATE_RANDOM_SECRET_32_CHARS>"
  max_age: 3600  # 1 hour
