networks:
  cloak-apps-net:
    external: false
    name: cloak-apps-net

volumes:
  keycloak-db:
    labels:
      - "dev.cloakapps.description=Keycloak own database storage"

services:
  cloak-apps:
    container_name: cloak-apps
    image: effiware/cloak-apps:${BUILD_VERSION:-0.0.1}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVER_VERSION: ${BUILD_VERSION:-0.0.1}
        BUILD_HASH: ${BUILD_HASH:-abcd123}
    platform: linux/amd64
    restart: unless-stopped
    profiles:
      - whole
    depends_on:
      - keycloak
    networks:
      - cloak-apps-net
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
      - "${TEMPL_PROXY_PORT}:${TEMPL_PROXY_PORT}"
    environment:
      - CLOAKAPPS_SERVER_ENVIRONMENT=${ENV}
      - CLOAKAPPS_SERVER_PORT=${SERVER_PORT}
      - CLOAKAPPS_KEYCLOAK_URL=http://keycloak:${KEYCLOAK_PORT}
      - CLOAKAPPS_KEYCLOAK_REDIRECT_URI=http://localhost:${SERVER_PORT}/auth/callback
      - CLOAKAPPS_OTLP_URL=http://jaeger:${JAEGER_HTTP_PORT:-4318}
    volumes:
      - ./config.yaml:/app/config.yaml:ro

  keycloak:
    image: quay.io/keycloak/keycloak:26.2
    container_name: cloak-apps-keycloak
    depends_on:
      - keycloak-db
    networks:
      - cloak-apps-net
    ports:
      - "${KEYCLOAK_PORT}:${KEYCLOAK_PORT}"
      - "443:443"
    restart: unless-stopped
    volumes:
      - ./keycloak-server.crt.pem:/opt/keycloak/keycloak-server.crt.pem:ro
      - ./keycloak-server.key.pem:/opt/keycloak/keycloak-server.key.pem:ro
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: keycloak-db
      KC_DB_URL_DATABASE: keycloak
      KC_DB_PASSWORD: STRONG_DB_PASSWORD2
      KC_DB_USERNAME: keycloak
      KC_DB_SCHEMA: public
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
      # --hostname=http://auth.cloakapps.localhost
    command: |
      start-dev
      --http-enabled=true
      --http-port=${KEYCLOAK_PORT}
      --https-port=443
      --hostname-strict=false
      --https-certificate-file=/opt/keycloak/keycloak-server.crt.pem
      --https-certificate-key-file=/opt/keycloak/keycloak-server.key.pem
      -Dkeycloak.profile.feature.token_exchange=enabled
      -Dkeycloak.profile.feature.admin_fine_grained_authz=enabled

  keycloak-db:
    image: postgres:16-alpine
    container_name: cloak-apps-keycloak-db
    networks:
      - cloak-apps-net
    volumes:
      - keycloak-db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: STRONG_DB_PASSWORD2

  jaeger:
    image: jaegertracing/jaeger:2.14.1
    container_name: cloak-apps-jaeger
    restart: unless-stopped
    profiles:
      - whole
    depends_on:
      - keycloak
    ports:
      - "${JAEGER_UI_PORT}:16686"
      - "${JAEGER_GRPC_PORT:-4317}:4317"
      - "${JAEGER_HTTP_PORT:-4318}:4318"
    environment:
      - LOG_LEVEL=debug
    networks:
      - cloak-apps-net

  prometheus:
    image: prom/prometheus:v3.4.0
    container_name: cloak-apps-prometheus
    restart: unless-stopped
    profiles:
      - whole
    ports:
      - "${PROMETHEUS_PORT}:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-lifecycle'
    networks:
      - cloak-apps-net